<a href="https://colab.research.google.com/github/Faizaa01/Python-for-ML/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr = np.array([1,2,3])
arr = arr*5
print(arr)
print(type(arr))
print(f"Dimebsion:{arr.ndim}, Shape:{arr.shape}, Dtype:{arr.dtype}, Size:{arr.size}")

arr2d = np.array([[1,2,3],
                 [4,5,6]])
print(f"Dimebsion:{arr2d.ndim}, Shape:{arr2d.shape}, Dtype:{arr2d.dtype}, Size:{arr2d.size}")

arr3d = np.array([[ [1,2,3],
                    [4,5,6]],

                  [ [7,8,9],
                    [10,11,12]],

                  [ [13,14,15],
                    [16,17,18] ]
                  ])
print(f"Dimebsion:{arr3d.ndim}, Shape:{arr3d.shape}, Dtype:{arr3d.dtype}, Size:{arr3d.size}")

[ 5 10 15]
<class 'numpy.ndarray'>
Dimebsion:1, Shape:(3,), Dtype:int64, Size:3
Dimebsion:2, Shape:(2, 3), Dtype:int64, Size:6
Dimebsion:3, Shape:(3, 2, 3), Dtype:int64, Size:18


In [ ]:
a = np.array([1,2,3])
a = a.astype(np.int32)
print(a.dtype)
ar = np.array([1, 2, 3], dtype=np.int8) #-127 to 127
print(ar.dtype)
arr = np.array([1, 2.4, 3.5])
print(arr.dtype)
arr1 = np.array([1, "2", 3.5])
print(arr1.dtype)

int32
int8
float64
<U32


In [ ]:
lst = [10,20,30,40.5]
a = np.array(lst)
print(a)
print(type(a))
print(a.dtype)

[10.  20.  30.  40.5]
<class 'numpy.ndarray'>
float64


In [ ]:
# a = {1,2,3,4} / (1,2,3,4)
# arr = np.array(list(a))
# a = {"aa":33,"bb":55}
# arr = np.array(list(a.items()))
arr = np.zeros((2,3))
# ar = np.zeros_like(arr3d)
# arr = np.ones((3,2,3))
# arr = np.full((4,3),10)
# arr = np.full((2,3),np.inf)
# arr = np.random.rand(2,3)
# arr = np.random.randint(1, 10, (4,3))
# arr = np.random.uniform(50,70, (3,4)) #with float
# arr = np.arange(1, 10, 2)
# arr = np.arange(1, 10, 1).reshape(3, 3)
# arr = np.linspace(1, 10, 5) #same distance from 1 to 10, 11 elements
# arr = np.logspace(1, 5, 5, base=2)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.size)
print(arr.ndim)


[[0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>
float64
(2, 3)
6
2


In [ ]:
diagonal_matrix = np.diag([1,2,3,4])
print(diagonal_matrix,"\n")
identity_mat = np.eye(3)
identity_mat1 = np.eye(3,4)
# identity_mat1 = np.eye(3,4,-1)
# identity_mat1 = np.eye(3,4,1)
print(identity_mat,"\n")
print(identity_mat1,"\n")

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]] 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]] 



In [ ]:
print(arr2d)
row_0 = arr2d[0:1, ]
row_1 = arr2d[1:, ]
col_0 = arr2d[::,0:1]
col_1 = arr2d[::,1:2]
print(row_0)
print(row_1)
print(col_0)
print(col_1)
x = arr2d[::, 0:2]
print(x)

[[1 2 3]
 [4 5 6]]
[[1 2 3]]
[[4 5 6]]
[[1]
 [4]]
[[2]
 [5]]
[[1 2]
 [4 5]]


In [ ]:
arr = np.array([1,2,3,4,5])
arr_new = arr[1:4].copy()
arr_new[0]=10
print(arr)
print(arr_new)

[1 2 3 4 5]
[10  3  4]


In [ ]:
lst = np.array([10,20,30,40])
values = lst[[0,3,1]]
print(values)

[10 40 20]


In [ ]:
print(arr2d)
print(arr2d[[0,1], [1,2]])
a = arr2d.copy()
a[a%2==0]=0
print(a)

[[1 2 3]
 [4 5 6]]
[2 6]
[[1 0 3]
 [0 5 0]]


In [ ]:
arr = np.array([[10,20,30],[40,50,60]])
for i in np.nditer(arr):
  print(i)

10
20
30
40
50
60


In [ ]:
a = np.random.randint(1,10, size=(6,3))
print(arr)
a.shape
b=a.reshape(3,6)
b

[[5 8 4]
 [6 6 4]
 [8 9 6]
 [6 1 6]
 [8 6 4]
 [7 4 3]]


array([[3, 9, 4, 2, 3, 9],
       [5, 3, 2, 4, 9, 9],
       [7, 4, 8, 7, 1, 4]])

In [ ]:
f = b.flatten()
f.ndim
print(f)

col_wise_flatten = np.ravel(b, order="F")
col_wise_flatten

[3 9 4 2 3 9 5 3 2 4 9 9 7 4 8 7 1 4]


array([3, 5, 7, 9, 3, 4, 4, 2, 8, 2, 4, 7, 3, 9, 1, 9, 9, 4])

In [ ]:
a = np.random.randint(1,10, size=(2,3))
b = np.random.randint(10,20, size=(2,3))
a,b

(array([[8, 1, 6],
        [5, 9, 4]]),
 array([[14, 10, 12],
        [11, 16, 11]]))

In [ ]:
con = np.concatenate((a,b), axis=0) #row wise
print(con)
con1 = np.concatenate((a,b), axis=1) #column wise
print(con1)

[[ 8  1  6]
 [ 5  9  4]
 [14 10 12]
 [11 16 11]]
[[ 8  1  6 14 10 12]
 [ 5  9  4 11 16 11]]


In [ ]:
mat = np.array([[10,20,30],
                [30,40,50]
               ])
transpose = mat.T
print(transpose)

a = np.random.randint(1 ,10 , size =(10,))
print(a)
splitted_array = np.array_split(a,3)
print(splitted_array)

[[10 30]
 [20 40]
 [30 50]]
[9 2 8 8 8 5 9 4 2 8]
[array([9, 2, 8, 8]), array([8, 5, 9]), array([4, 2, 8])]


In [ ]:
x = np.array([ 10 , 8 , 30 , 100 ])
y = np.array([ 2 , 3 ,4  ,5 ])
add=np.add(x,y) #x+y
sub=np.subtract(x,y) #x-y
mul=np.multiply(x,y) #x*y
div=np.divide(x,y) # x/y
remainder = x % y
print(add)
print(sub)
print(mul)
print(div)
print(remainder)

sin_val = np.sin(x)
print(sin_val)

cos_val = np.cos(x)
print(cos_val)

deg_con = np.rad2deg(x)
print(deg_con)

[ 12  11  34 105]
[ 8  5 26 95]
[ 20  24 120 500]
[ 5.          2.66666667  7.5        20.        ]
[0 2 2 0]
[-0.54402111  0.98935825 -0.98803162 -0.50636564]
[-0.83907153 -0.14550003  0.15425145  0.86231887]
[ 572.95779513  458.3662361  1718.87338539 5729.57795131]


In [ ]:
x = np.array([10, 8, 6, 16])
res = x**2
print(res)

matrix = np.array([[10,20,30],
                   [30,40,50] ])
result = matrix + 2

vector = np.array([1,2,3])
result = matrix +vector
print(result)

greater_than = x>y
print(greater_than)
equal = x==y
print(np.all(greater_than))
print(np.any(equal))

z = x.copy()
# z=np.sort(x)
z.sort()
print(z)

mat = np.array([[10,3,5],[8,4,9]])
hor_sort = np.sort(mat,axis=1)
print(hor_sort)
vert_sort = np.sort(mat,axis=0)
print(vert_sort)

[100  64  36 256]
[[11 22 33]
 [31 42 53]]
[ True  True  True  True]
True
False
[ 6  8 10 16]
[[ 3  5 10]
 [ 4  8  9]]
[[ 8  3  5]
 [10  4  9]]


In [ ]:
idx = np.where(x==8)
print(idx)
idx = np.where(x>8)
# idx = np.where(x>8, x,0)
print(idx)

(array([1]),)
(array([0, 3]),)


In [ ]:
a = np.random.randint(1 ,100 , size =(100,))
print(a)

[71  5 21 41 64 59 88 40 16 75 31 71 40 81 48 28 40  8 81 41 87 20 47  4
 91 39 30  8 87 76 53 45 90 62 72 50 94 87 33 23 60 48 81 15 70 84 63 16
 82 37 32  1 20 82 10 48 58 71  2  2 45 13 13 29  4 31 90 76 38  6 95 88
 85  1  5 46  1 53 76 92 55 79 77 93  9  6 63 39  2 84 84 91 27 83 13 44
 77 47 26  1]


In [ ]:
value_great_than_60 = np.count_nonzero(a>91)
print(value_great_than_60)
unique_value,count = np.unique(a,return_counts=True)
print(unique_value)
print(count)

4
[ 1  2  4  5  6  8  9 10 13 15 16 20 21 23 26 27 28 29 30 31 32 33 37 38
 39 40 41 44 45 46 47 48 50 53 55 58 59 60 62 63 64 70 71 72 75 76 77 79
 81 82 83 84 85 87 88 90 91 92 93 94 95]
[4 3 2 2 2 2 1 1 3 1 2 2 1 1 1 1 1 1 1 2 1 1 1 1 2 3 2 1 2 1 2 3 1 2 1 1 1
 1 1 2 1 1 3 1 1 3 2 1 3 2 1 3 1 3 2 2 2 1 1 1 1]


In [ ]:
x = np.array([ 10,100 , 8 , 16 , 100 ])

maximum_value_indx = np.argmax(x)
minimum_value_indx = np.argmin(x)

print(maximum_value_indx)
print(minimum_value_indx)

1
2


In [ ]:
study_hours = np.array([2, 4, 5, 7, 8])
exam_scores = np.array([65, 75, 78, 88, 92])

data = np.array([study_hours, exam_scores])
correlation = np.corrcoef(data)
print("Correlation Matrix:\n", correlation)

Correlation Matrix:
 [[1.         0.99859154]
 [0.99859154 1.        ]]


In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
B = np.array([
    [7, 8],
    [9, 10],
    [11, 12]
])

dot_product = np.dot(A,B)
print(dot_product)
print(np.trace(B))

sq_mat = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

determinant = np.linalg.det(sq_mat)
print(determinant)
rank_sq = np.linalg.matrix_rank(sq_mat)
print(rank_sq)

[[ 58  64]
 [139 154]]
17
0.0
2


0.0
2
